-- return {
-- 	"akinsho/bufferline.nvim",
-- 	dependencies = { "nvim-tree/nvim-web-devicons" },
-- 	version = "*",
-- 	event = "VeryLazy",
-- 	opts = {
-- 		options = {
-- 			mode = "tabs",
-- 			hover = {
-- 				enabled = true,
-- 				delay = 200,
-- 				reveal = { "close" },
-- 			},
-- 		},
-- 	},
-- }
return {}
