return {
	"zaldih/themery.nvim",
	lazy = false,
	config = function()
		require("themery").setup({
			themes = {
				"rose-pine",
				"rose-pine-dawn",
				"rose-pine-moon",
				"vesper",
				"sonokai",
				"tokyonight-night",
				"tokyonight-storm",
				"tokyonight-day",
				"tokyonight-moon",
				"ayu",
				"ayu-dark",
				"ayu-light",
				"catppuccin-latte",
				"catppuccin-mocha",
				"catppuccin-macchiato",
				"catppuccin-frappe",
				"gruvbox",
				"kanagawa",
				"horizon",
				"solarized-osaka",
				"material-oceanic",
				"material-deep-ocean",
				"material-palenight",
				"material-lighter",
				"material-darker",
				"astrodark",
				"astrojupiter",
				"astrolight",
				"astromars",
				"astrotheme",
			},
		})
	end,
	keys = {
		{ "<leader>th", "<cmd>Themery<cr>", desc = "Change Theme" },
	},
}
